export let CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
export let REQUEST_ROBOTS_PENDING = 'REQUEST_ROBOTS_PENDING' ;
export let REQUEST_ROBOTS_SUCCESS = 'REQUEST_ROBOTS_SUCCESS' ;
export let REQUEST_ROBOTS_FAILED = 'REQUEST_ROBOTS_FAILED' ;